### ISSUE TITLE
Security Related matters

### ISSUE THREAD

**Issue by SIT-EddieTan** [INF2001-Team10-6/Software-Project#22]
Website safety and security requirements are essential to protect your website and its users from various threats, including cyberattacks, data breaches, and other malicious activities. Implementing these requirements helps ensure the confidentiality, integrity, and availability of your website and its data.

**Comment by yurjere** [comment]
1. HTTPS Encryption
2. Strong Authentication
3. Access Control
4. Data Encryption
5. User Data Protection
6. Legal and Compliance Requirements
7. Security Audits

**Comment by yurjere** [comment]
done
