### ISSUE TITLE
[1.18] User Graphic Requirement

### ISSUE THREAD

**Issue by SIT-EddieTan** [INF2001-Team10-6/Software-Project#46]
Low Fidelity Prototype of website with descriptions of how the different webpages are linked

**Comment by INF2001-Team10-6** [comment]
Low Fidelity Prototype of website with descriptions of how the different webpages are linked

**Comment by ESLunarPhoenix** [comment]
Low Fidelity Prototype of website with descriptions of how the different webpages are linked

**Comment by ESLunarPhoenix** [comment]
Low Fidelity Prototype of website with descriptions of how the different webpages are linked
